### ISSUE TITLE
Failed to deploy KITInfrastructure CDK

### ISSUE THREAD

**Issue by mengqiy** [awslabs/kubernetes-iteration-toolkit#313]
I can't deploy CDK in my own account with the following error: `TooManyRequestsException: Rate Exceeded.`

<details>
<summary>
Complete output
</summary>

```
$ cdk deploy KITInfrastructure --no-rollback \
  -c TestFluxRepoName="davidyukit" \
  -c TestFluxRepoURL="https://github.com/mengqiy/kubernetes-iteration-toolkit" \
  -c TestFluxRepoBranch="testcdk" \
  -c TestFluxRepoPath="./test/infrastructure/clusters/test-infra" \
  -c TestNamespace="davidyu-tests" \
  -c TestServiceAccount="davidyu-tests"
[Warning at /KITInfrastructure/NodeSecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customized rules, set allowAllOutbound=false on the SecurityGroup
[Warning at /KITInfrastructure/NodeSecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customized rules, set allowAllOutbound=false on the SecurityGroup

✨  Synthesis time: 6.72s

KITInfrastructure: building assets...

[0%] start: Building 4288ebb3652acdf2d828b7db7ca44a7162a401ace50ebb4026e84b18a02a06ee:current_account-current_region
[0%] start: Building 04a62144012b2cd32474867b1533a36eb328db26f983a17ff81189234aff4705:current_account-current_region
[0%] start: Building 23e8dd0cd843d112224968307ac764ce3fc2f2ddea65eb8c8c8feb8f48e660d3:current_account-current_region
[0%] start: Building d01d4b7367b49a3e222279017fe50e41d6b2272d436b2e82038d0036deb2cdcb:current_account-current_region
[0%] start: Building 823f6b284b7398541ad875711f17011724c206ee7fbbd046c66f171875c66c66:current_account-current_region
[0%] start: Building c6964dbf0c556ec82ce09622e99ad6f6d4e488cdaac0ef9e8492e078ec61ffed:current_account-current_region
[0%] start: Building f7f53a92c36d534d2a91a241257f20f748d85f700dac48fafe14bfdbc36eaad5:current_account-current_region
[0%] start: Building ef28ae71a763ab8539c2c2de8af41b50e7a1e293d91583c5a55d275b40a23cc0:current_account-current_region
[0%] start: Building 6fa6f3b12993b4002f6ef146cbef8b3396c2be73e4e6a06aa289c2f42786d15e:current_account-current_region
[0%] start: Building 6a4e3d120529dec08bd7b81445f21cae0fec05e147a449d8988c81dfdf59aa21:current_account-current_region
[0%] start: Building 5da69aecbbe7220ba7537b51e4ff92f7a57bc8b08bc06bdb7faeda4d0c134966:current_account-current_region                                                                                                                                   [73/1812]
[9%] success: Built 4288ebb3652acdf2d828b7db7ca44a7162a401ace50ebb4026e84b18a02a06ee:current_account-current_region
[18%] success: Built 04a62144012b2cd32474867b1533a36eb328db26f983a17ff81189234aff4705:current_account-current_region
[27%] success: Built 23e8dd0cd843d112224968307ac764ce3fc2f2ddea65eb8c8c8feb8f48e660d3:current_account-current_region
[36%] success: Built d01d4b7367b49a3e222279017fe50e41d6b2272d436b2e82038d0036deb2cdcb:current_account-current_region
[45%] success: Built 823f6b284b7398541ad875711f17011724c206ee7fbbd046c66f171875c66c66:current_account-current_region
[54%] success: Built c6964dbf0c556ec82ce09622e99ad6f6d4e488cdaac0ef9e8492e078ec61ffed:current_account-current_region
[63%] success: Built f7f53a92c36d534d2a91a241257f20f748d85f700dac48fafe14bfdbc36eaad5:current_account-current_region
[72%] success: Built ef28ae71a763ab8539c2c2de8af41b50e7a1e293d91583c5a55d275b40a23cc0:current_account-current_region
[81%] success: Built 6fa6f3b12993b4002f6ef146cbef8b3396c2be73e4e6a06aa289c2f42786d15e:current_account-current_region
[90%] success: Built 6a4e3d120529dec08bd7b81445f21cae0fec05e147a449d8988c81dfdf59aa21:current_account-current_region
[100%] success: Built 5da69aecbbe7220ba7537b51e4ff92f7a57bc8b08bc06bdb7faeda4d0c134966:current_account-current_region

KITInfrastructure: assets built

KITInfrastructure: deploying...
[0%] start: Publishing 4288ebb3652acdf2d828b7db7ca44a7162a401ace50ebb4026e84b18a02a06ee:current_account-current_region
[0%] start: Publishing 04a62144012b2cd32474867b1533a36eb328db26f983a17ff81189234aff4705:current_account-current_region
[0%] start: Publishing 23e8dd0cd843d112224968307ac764ce3fc2f2ddea65eb8c8c8feb8f48e660d3:current_account-current_region
[0%] start: Publishing d01d4b7367b49a3e222279017fe50e41d6b2272d436b2e82038d0036deb2cdcb:current_account-current_region
[0%] start: Publishing 823f6b284b7398541ad875711f17011724c206ee7fbbd046c66f171875c66c66:current_account-current_region
[0%] start: Publishing c6964dbf0c556ec82ce09622e99ad6f6d4e488cdaac0ef9e8492e078ec61ffed:current_account-current_region
[0%] start: Publishing f7f53a92c36d534d2a91a241257f20f748d85f700dac48fafe14bfdbc36eaad5:current_account-current_region
[0%] start: Publishing ef28ae71a763ab8539c2c2de8af41b50e7a1e293d91583c5a55d275b40a23cc0:current_account-current_region
[0%] start: Publishing 6fa6f3b12993b4002f6ef146cbef8b3396c2be73e4e6a06aa289c2f42786d15e:current_account-current_region
[0%] start: Publishing 6a4e3d120529dec08bd7b81445f21cae0fec05e147a449d8988c81dfdf59aa21:current_account-current_region
[0%] start: Publishing 5da69aecbbe7220ba7537b51e4ff92f7a57bc8b08bc06bdb7faeda4d0c134966:current_account-current_region
[9%] success: Published 6fa6f3b12993b4002f6ef146cbef8b3396c2be73e4e6a06aa289c2f42786d15e:current_account-current_region
[18%] success: Published 04a62144012b2cd32474867b1533a36eb328db26f983a17ff81189234aff4705:current_account-current_region
[27%] success: Published 823f6b284b7398541ad875711f17011724c206ee7fbbd046c66f171875c66c66:current_account-current_region
[36%] success: Published c6964dbf0c556ec82ce09622e99ad6f6d4e488cdaac0ef9e8492e078ec61ffed:current_account-current_region
[45%] success: Published 5da69aecbbe7220ba7537b51e4ff92f7a57bc8b08bc06bdb7faeda4d0c134966:current_account-current_region
[54%] success: Published 23e8dd0cd843d112224968307ac764ce3fc2f2ddea65eb8c8c8feb8f48e660d3:current_account-current_region
[63%] success: Published f7f53a92c36d534d2a91a241257f20f748d85f700dac48fafe14bfdbc36eaad5:current_account-current_region
[72%] success: Published 4288ebb3652acdf2d828b7db7ca44a7162a401ace50ebb4026e84b18a02a06ee:current_account-current_region
[81%] success: Published 6a4e3d120529dec08bd7b81445f21cae0fec05e147a449d8988c81dfdf59aa21:current_account-current_region
[90%] success: Published d01d4b7367b49a3e222279017fe50e41d6b2272d436b2e82038d0036deb2cdcb:current_account-current_region
[100%] success: Published ef28ae71a763ab8539c2c2de8af41b50e7a1e293d91583c5a55d275b40a23cc0:current_account-current_region
KITInfrastructure: creating CloudFormation changeset...
11:10:19 PM | CREATE_FAILED        | Custom::AWSCDK-EKS-KubernetesResource | ClustermanifestTestGitRepoSelf8C19696C
Received response status [FAILED] from custom resource. Message returned: TooManyRequestsException: Rate Exceeded.
at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:49:8)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12) (RequestId: 31e333fc-14a6-427a-a769-d1224d301883)

11:10:19 PM | CREATE_FAILED        | Custom::AWSCDK-EKS-KubernetesResource | ClustermanifestTes...zationSelf62097B36
Received response status [FAILED] from custom resource. Message returned: TooManyRequestsException: Rate Exceeded.
at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:49:8)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12) (RequestId: 11871cb7-74e1-4ca1-be91-f67f73734d08)


 ❌  KITInfrastructure failed: Error: The stack named KITInfrastructure failed to deploy: UPDATE_FAILED (The following resource(s) failed to create: [ClustermanifestTestGitRepoSelf8C19696C, ClustermanifestTestAddonKustomizationSelf62097B36]. ): Received reponse status [FAILED] from custom resource. Message returned: TooManyRequestsException: Rate Exceeded.
    at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:49:8)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12) (RequestId: 31e333fc-14a6-427a-a769-d1224d301883), Received response status [FAILED] from custom resource. Message returned: TooManyRequestsException: Rate Exceeded.
    at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:49:8)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12) (RequestId: 11871cb7-74e1-4ca1-be91-f67f73734d08)
    at FullCloudFormationDeployment.monitorDeployment (/local/home/mengqiyu/.nvm/versions/node/v16.18.0/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:505:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at deployStack2 (/local/home/mengqiyu/.nvm/versions/node/v16.18.0/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:241:24)
    at /local/home/mengqiyu/.nvm/versions/node/v16.18.0/lib/node_modules/aws-cdk/lib/deploy.ts:39:11
    at run (/local/home/mengqiyu/.nvm/versions/node/v16.18.0/lib/node_modules/p-queue/dist/index.js:163:29)

 ❌ Deployment failed: Error: Stack Deployments Failed: Error: The stack named KITInfrastructure failed to deploy: UPDATE_FAILED (The following resource(s) failed to create: [ClustermanifestTestGitRepoSelf8C19696C, ClustermanifestTestAddonKustomizationSelf2097B36]. ): Received response status [FAILED] from custom resource. Message returned: TooManyRequestsException: Rate Exceeded.
    at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:49:8)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12) (RequestId: 31e333fc-14a6-427a-a769-d1224d301883), Received response status [FAILED] from custom resource. Message returned: TooManyRequestsException: Rate Exceeded.
    at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:49:8)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12) (RequestId: 11871cb7-74e1-4ca1-be91-f67f73734d08)
    at deployStacks (/local/home/mengqiyu/.nvm/versions/node/v16.18.0/lib/node_modules/aws-cdk/lib/deploy.ts:61:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at CdkToolkit.deploy (/local/home/mengqiyu/.nvm/versions/node/v16.18.0/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:315:7)
    at initCommandLine (/local/home/mengqiyu/.nvm/versions/node/v16.18.0/lib/node_modules/aws-cdk/lib/cli.ts:358:12)

Stack Deployments Failed: Error: The stack named KITInfrastructure failed to deploy: UPDATE_FAILED (The following resource(s) failed to create: [ClustermanifestTestGitRepoSelf8C19696C, ClustermanifestTestAddonKustomizationSelf62097B36]. ): Received respons
e status [FAILED] from custom resource. Message returned: TooManyRequestsException: Rate Exceeded.
    at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:49:8)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12) (RequestId: 31e333fc-14a6-427a-a769-d1224d301883), Received response status [FAILED] from custom resource. Message returned: TooManyRequestsException: Rate Exceeded.
    at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:49:8)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12) (RequestId: 11871cb7-74e1-4ca1-be91-f67f73734d08)
```
</details>

It's clear what's root cause of this problem.

**Comment by mengqiy** [comment]
cc: @hakuna-matatah @prateekgogia Any idea what's going on?

**Comment by mengqiy** [comment]
I forgot to update this earlier. I made a change in my CDK that cause a problem when deploying it. So the error above is legitimate though it's not very user friendly. 
Closing this issue
