### ISSUE TITLE
[operator] KIT Controller restarting continuously, it couldn't come up healthy 

### ISSUE THREAD

**Issue by hakuna-matatah** [awslabs/kubernetes-iteration-toolkit#76]
[operator] KIT Controller restarting continuously, it couldn't come up healthy.

```
I1123 15:10:54.158002       1 request.go:655] Throttling request took 1.0440526s, request: GET:https://172.20.0.1:443/apis/authorization.k8s.io/v1?timeout=32s
2021-11-23T15:10:54.261Z	INFO	controller-runtime.metrics	metrics server is starting to listen	{"addr": ":8080"}
2021-11-23T15:10:54.262Z	INFO	controller-runtime.builder	skip registering a mutating webhook, admission.Defaulter interface is not implemented	{"GVK": "kit.k8s.sh/v1alpha1, Kind=ControlPlane"}
2021-11-23T15:10:54.262Z	INFO	controller-runtime.builder	skip registering a validating webhook, admission.Validator interface is not implemented	{"GVK": "kit.k8s.sh/v1alpha1, Kind=ControlPlane"}
2021-11-23T15:10:54.262Z	INFO	controller-runtime.builder	skip registering a mutating webhook, admission.Defaulter interface is not implemented	{"GVK": "kit.k8s.sh/v1alpha1, Kind=DataPlane"}
2021-11-23T15:10:54.262Z	INFO	controller-runtime.builder	skip registering a validating webhook, admission.Validator interface is not implemented	{"GVK": "kit.k8s.sh/v1alpha1, Kind=DataPlane"}
I1123 15:10:54.263057       1 leaderelection.go:243] attempting to acquire leader lease kit/kit-leader-election...
2021-11-23T15:10:54.263Z	INFO	controller-runtime.manager	starting metrics server	{"path": "/metrics"}
I1123 15:11:11.689185       1 leaderelection.go:253] successfully acquired lease kit/kit-leader-election
2021-11-23T15:11:11.689Z	INFO	controller-runtime.manager.controller.dataplane	Starting EventSource	{"reconciler group": "kit.k8s.sh", "reconciler kind": "DataPlane", "source": "kind source: /, Kind="}
2021-11-23T15:11:11.689Z	INFO	controller-runtime.manager.controller.control-plane	Starting EventSource	{"reconciler group": "kit.k8s.sh", "reconciler kind": "ControlPlane", "source": "kind source: /, Kind="}
I1123 15:11:12.738906       1 request.go:655] Throttling request took 1.047619315s, request: GET:https://172.20.0.1:443/apis/rbac.authorization.k8s.io/v1?timeout=32s
2021-11-23T15:11:12.840Z	ERROR	controller-runtime.source	if kind is a CRD, it should be installed before calling Start	{"kind": "DataPlane.kit.k8s.sh", "error": "no matches for kind \"DataPlane\" in version \"kit.k8s.sh/v1alpha1\""}
2021-11-23T15:11:15.489Z	ERROR	controller-runtime.source	if kind is a CRD, it should be installed before calling Start	{"kind": "ControlPlane.kit.k8s.sh", "error": "no matches for kind \"ControlPlane\" in version \"kit.k8s.sh/v1alpha1\""}
2021-11-23T15:11:15.490Z	ERROR	controller-runtime.manager	error received after stop sequence was engaged	{"error": "no matches for kind \"ControlPlane\" in version \"kit.k8s.sh/v1alpha1\""}
2021-11-23T15:11:15.490Z	ERROR	controller-runtime.manager	error received after stop sequence was engaged	{"error": "leader election lost"}
panic: Unable to start manager, no matches for kind "DataPlane" in version "kit.k8s.sh/v1alpha1"

goroutine 1 [running]:
main.main()
	github.com/awslabs/kit/operator/cmd/controller/main.go:64 +0x86a

```

**Comment by prateekgogia** [comment]
Is this still an issue? Feel free to reopen if you are seeing this still.

**Comment by hakuna-matatah** [comment]
> Is this still an issue? Feel free to reopen if you are seeing this still.

I think this issue happens in `0.3` IIRC. I couldn't upgrade it to `0.4` where the fix is in place due to CRD spec missing issue. Could we use this Issue to fix CRD spec issue so upgrade could work fine ? (Reference - More info about this in our KIT Slack channel )
